In [1]:
import pandas as pd
df = pd.read_csv("Dataset1.csv")
df.head()

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [2]:
df.isnull().sum()

SN                0
Train_No          0
Station_Code      0
1A                0
2A                0
3A                0
SL                0
Station_Name      0
Route_Number      0
Arrival_time      0
Departure_Time    0
Distance          0
dtype: int64

In [3]:
df = df.drop_duplicates()

In [4]:
df.duplicated().sum()

0

In [6]:
df["Arrival_time"] = pd.to_datetime(
    df["Arrival_time"],
    format="%H:%M:%S",
    errors="coerce"
)

df["Departure_Time"] = pd.to_datetime(
    df["Departure_Time"],
    format="%H:%M:%S",
    errors="coerce"
)

In [7]:
df[["Arrival_time", "Departure_Time"]].head()

         Arrival_time      Departure_Time
0 2026-01-17 00:00:00 2026-01-17 10:25:00
1 2026-01-17 11:06:00 2026-01-17 11:08:00
2 2026-01-17 11:28:00 2026-01-17 11:30:00
3 2026-01-17 12:10:00 2026-01-17 00:00:00
4 2026-01-17 00:00:00 2026-01-17 20:30:00

In [8]:
journey_duration = df.groupby("Train_No").agg(
    Start_Time=("Arrival_time", "min"),
    End_Time=("Departure_Time", "max")
)

journey_duration["Journey_Duration_Hours"] = (
    journey_duration["End_Time"] - journey_duration["Start_Time"]
).dt.total_seconds() / 3600

journey_duration.head()

                  Start_Time            End_Time  Journey_Duration_Hours
Train_No
107      2026-01-17 00:00:00 2026-01-17 11:30:00               11.500000
108      2026-01-17 00:00:00 2026-01-17 21:28:00               21.466667
128      2026-01-17 00:34:00 2026-01-17 23:57:00               23.383333
290      2026-01-17 00:05:00 2026-01-17 22:55:00               22.833333
401      2026-01-17 01:15:00 2026-01-17 23:55:00               22.666667

In [9]:
total_distance = df.groupby("Train_No")["Distance"].max()

In [10]:
num_stops = df.groupby("Train_No")["Station_Code"].count()

In [11]:
train_features = pd.concat(
    [total_distance, num_stops, journey_duration["Journey_Duration_Hours"]],
    axis=1
)

train_features.columns = [
    "Total_Distance",
    "Number_of_Stops",
    "Journey_Duration_Hours"
]

train_features.head()

          Total_Distance  Number_of_Stops  Journey_Duration_Hours
Train_No
107                   78                4               11.500000
108                   83                4               21.466667
128                  978               22               23.383333
290                 2694               14               22.833333
401                 1618               12               22.666667

In [12]:
journey_duration = df.groupby("Train_No").agg(
    Start_Time=("Arrival_time", "min"),
    End_Time=("Departure_Time", "max")
)

journey_duration["Journey_Duration_Hours"] = (
    journey_duration["End_Time"] - journey_duration["Start_Time"]
).dt.total_seconds() / 3600

journey_duration.head()

                  Start_Time            End_Time  Journey_Duration_Hours
Train_No
107      2026-01-17 00:00:00 2026-01-17 11:30:00               11.500000
108      2026-01-17 00:00:00 2026-01-17 21:28:00               21.466667
128      2026-01-17 00:34:00 2026-01-17 23:57:00               23.383333
290      2026-01-17 00:05:00 2026-01-17 22:55:00               22.833333
401      2026-01-17 01:15:00 2026-01-17 23:55:00               22.666667